Import('env')

sources = Split("""
                svecmat_test.cpp
                quaternion_test.cpp
                mystring_test.cpp
                object_test.cpp
                objectwithparameters_test.cpp
                value_test.cpp
                range_test.cpp
                fitparameter_test.cpp
                source_test.cpp
                axe_test.cpp
                geometry_test.cpp
                geometry_eulerian4C_test.cpp
                geometry_eulerian6C_test.cpp
                geometry_kappa4C_test.cpp
                geometry_kappa6C_test.cpp
                reflection_test.cpp
                crystal_test.cpp
                crystallist_test.cpp
                mode_eulerian4C_test.cpp
                mode_kappa4C_test.cpp
                mode_kappa6C_test.cpp
                pseudoaxe_eulerian4C_test.cpp
                pseudoaxe_kappa4C_test.cpp
                affinement_simplex_test.cpp
                diffractometer_eulerian4C_test.cpp
                diffractometer_kappa4C_test.cpp
                diffractometer_kappa6C_test.cpp
                main.cpp
                """)

includes = ['#include/hkl']

obj = env.cppunitobj(env)
obj.includes = includes
obj.libpaths = ['../src']
obj.libs = ['hkl']
obj.target = 'test'
obj.source = sources
obj.execute()
