import os
Import('env')

sources = Split("""
                svecmat_test.cpp
                quaternion_test.cpp
                object_test.cpp
                objectwithparameters_test.cpp
                value_test.cpp
                range_test.cpp
                fitparameter_test.cpp
                source_test.cpp
                axe_test.cpp
                geometry_test.cpp
                reflection_test.cpp
                crystal_test.cpp
                crystallist_test.cpp
                mode_eulerian4C_test.cpp
                pseudoaxe_eulerian4C_test.cpp
                affinement_simplex_test.cpp
                diffractometer_eulerian4C_test.cpp
                libHKL_test.cpp
                """)


includes = Split("""
                 #include
                 """)
libpaths = '#src'

platform = env['PLATFORM']

if platform == 'posix':
  includes += ['#include/linux']
  libs = ['hkl']
elif platform in ['nt', 'win32']:
  includes += ['#include/win32']
  includes += CPPUNIT_INCLUDE
  #myenv.Append(LIBPATH = CPPUNIT_LIBPATH)
  #myenv.Append(LIBS = ['libhkl'])

obj = env.cppunitobj(env)
obj.includes = includes
obj.libpaths = libpaths
obj.libs = libs
obj.target = 'hkl-test'
obj.source = sources
obj.execute()
