#! /usr/bin/env python
# encoding: utf-8

obj = bld.new_task_gen('cc', 'program')
obj.find_sources_in_dirs('.')
obj.target = 'test'
obj.cflags = '-g'
obj.includes = '. ../include'
obj.unit_test = 1
obj.uselib = 'GSL'
obj.uselib_local = 'hkl'
obj.install_path = None
