#! /usr/bin/env python
# encoding: utf-8

obj = bld.new_task_gen(
	features = ['cc', 'cprogram'],
	target = 'test',
	cflags = '-g',
	includes = '. ../include',
	rpath = bld.bdir + '/default/src',
	unit_test = 1,
	uselib = 'GSL',
	uselib_local = 'hkl',
	install_path = None)
obj.find_sources_in_dirs('.')
obj.source.remove('./bench.c')

obj = bld.new_task_gen(
	features = ['cc', 'cprogram'],
	source = 'bench.c',
	target = 'bench',
	cflags = '-g',
	includes = '. ../include',
	rpath = bld.bdir + '/default/src',
	unit_test = 1,
	uselib = 'GSL',
	uselib_local = 'hkl',
	install_path = None)
