#ifndef _PSEUDOAXEENGINE_EULERIAN4C_H_
#define _PSEUDOAXEENGINE_EULERIAN4C_H_

#include "derivedpseudoaxeengine.h"
#include "geometry_eulerian4C.h"
#include "pseudoaxeengine_twoC.h"

using namespace std;

namespace hkl
  {
  namespace pseudoAxeEngine
    {
    namespace eulerian4C
      {
      namespace vertical
        {

        /**
         * @brief The eulerian 4-circle Vertical diffractometer Psi pseudoAxe.
         *
         * This pseudoAxe represent a rotation around the scattering vector \f$ \vec{Q} \f$.
         *
         * To compute this pseudoAxe we start from the fondamental equation
         * \f[
         *  R = \Omega \chi \phi
         * \f]
         * thus
         * \f[
         *  \left(
         *    \begin{matrix}
         *      \cos\omega \cos\phi - \cos\chi \sin\omega \sin\phi & -\sin\chi \sin\omega & -\cos\omega \sin\phi - \cos\chi \sin\omega \cos\phi \\
         *      -\sin\chi \sin\phi                                 & \cos\chi             & -\sin\chi \cos\phi \\
         *      \sin\omega \cos\phi - \cos\chi \cos\omega \sin\phi & \sin\chi \cos\omega  & -\sin\omega \sin\phi + \cos\chi \cos\omega \cos\phi
         *    \end{matrix}
         *  \right)
         * \f]
         * 
         * Now \f$\psi\f$ is the rotation angle around the scattering vector \f$\vec{Q}\f$.
         * So we can write:
         * \f[
         *  R = \Psi R_0
         * \f]
         * where \f$\Psi\f$ is the rotation matrix around the \f$\vec{Q}\f$ vector
         * and \f$R_0\f$ the \f$R\f$ matrix for \f$\Psi=0\f$
         * 
         * The 1st where \f$\sin\chi > 0\f$ is:
         * \f{eqnarray*}
         *  \omega & = & \arctan(-R_{0,1}, R_{2,1}) \\
         *  \chi & = & \arctan(\sqrt{R_{0,1}^2+R_{2,1}^2}, R_{1,1}) \\
         *  \phi & = & \arctan(-R_{1,0}, -R_{1,2})
         * \f}
         *
         * The 2nd one \f$\sin\chi < 0\f$ is:
         * \f{eqnarray*}
         *  \omega' & = & \arctan(R_{0,1}, -R_{2,1}) \\
         *  \chi' & = & \arctan(-\sqrt{R_{0,1}^2+R_{2,1}^2}, R_{1,1}) = -\chi\\
         *  \phi' & = & \arctan(R_{1,0}, R_{1,2})
         * \f}
         *
         * Thoses two solutions are not valid if \f$\chi=0\f$ or \f$\chi=\pi\f$.
         * In that case the \f$ R\f$ matrix can be simplify:
         * \f[
         *  \left(
         *    \begin{matrix}
         *      \pm\cos(\omega+\phi) & 0 & \mp\sin(\omega+\phi) \\
         *      0                 & \pm1 & 0 \\
         *      \pm\sin(\omega+\phi) & 0 & \pm\cos(\omega+\phi)
         *    \end{matrix}
         *  \right)
         * \f]
         */
        class Psi : public PseudoAxeEngineTemp<geometry::eulerian4C::Vertical>
          {
          public:

            /**
             * @brief The default constructor
             * @param geometry The related Geometry.
             */
            Psi(geometry::eulerian4C::Vertical & geometry);

            /**
             * @brief The default destructor.
             */
            ~Psi(void);

            void initialize(void) throw (HKLException);

            void uninitialize(void);

            /**
             * @brief Check if the PseudoAxe is Valid.
             * @return true if the PseudoAxe is valid, false otherwise.
             * @throw HKLException if the PseudoAxe is not valid.
             *
             * To be valid this angles of the detector must no move, and the
             * sample axes must perform a rotation around the scattering vector.
             */
            bool isValid(void) throw (HKLException);

            void update(void);

            void set(void) throw (HKLException);

            /*!
             * \brief Save the pseudoaxe::eulerian4C::Psi into a stream.
             * \param flux the stream to save the pseudoaxe::eulerian4C::Psi into.
             * \return The stream with the pseudoaxe::eulerian4C.
             */
            ostream & toStream(ostream & flux) const;

            /*!
             * \brief Restore a pseudoaxe::eulerian4C::Psi from a stream.
             * \param flux The stream containing the pseudoaxe::eulerian4C::Psi.
             */
            istream & fromStream(istream & flux);


          private:
            Axe * & _omega; //!< The omega axe use for calculation.
            Axe * & _chi; //!< The chi axe use for calculation.
            Axe * & _phi; //!< The phi axe use for calculation.
            Axe * & _tth; //!< The tth axe use for calculation.

            svector _Q0; //!< The scattering vector Q.
            Quaternion _qpsi0; //!< The quaternion of the machine after the initialisation.

            Range _psi_r; //!< The read part of the psi PseudoAxe.
            Range _psi_w; //!< the write part of the Psi PseudoAxe.

            PseudoAxe * _psi; //!< The psi PseudoAxe generated by this PseudoAxeEngine.
          };

        namespace twoC
          {

          typedef DerivedPseudoAxeEngine<pseudoAxeEngine::twoC::vertical::Th2th, geometry::eulerian4C::Vertical> Th2th; //!< DerivedPseudoAxe from the twoC pseudoAxes.
          typedef DerivedPseudoAxeEngine<pseudoAxeEngine::twoC::vertical::Q2th, geometry::eulerian4C::Vertical> Q2th; //!< DerivedPseudoAxe from the twoC pseudoAxes.
          typedef DerivedPseudoAxeEngine<pseudoAxeEngine::twoC::vertical::Q, geometry::eulerian4C::Vertical> Q; //!< DerivedPseudoAxe from the twoC pseudoAxes.

        } // namespace twoC
      } // namespace vertical.
    } // namespace eulerian4C.
  } // namespace pseudoAxeEngine.
} // namespace hkl.

#endif // _PSEUDOAXEENGINE_EULERIAN4C_H_
