Import('env')

sources = Split("""
                diffractometer_wrap.cpp
                diffractometer_kappa_wrap.cpp
                diffractometer_eulerian4C_wrap.cpp
                diffractometer_kappa4C_wrap.cpp
                hkl_wrap.cpp
                """)

obj = env.boost_pythonobj(env)
obj.vnum = '2.1.0'
obj.includes = ['#include/hkl']
obj.target = 'hkl'
obj.libpaths = ['../../src']
obj.libs = ['hkl']
obj.source = sources
obj.execute()

