Import('env')

sources = Split("""
                psi.cpp
                """)

includes = ['#include/hkl']

obj = env.genobj('program', env)
obj.includes = includes
obj.libpaths = ['../../src']
obj.libs = ['hkl']
obj.target = 'psi'
obj.source = sources
obj.execute()