#!/bin/bash
./cleanfile ../hkl/*.[ch] ../test/*.[ch] ../test/hkl/*.[ch] ../test/hkl3d/*.[ch] ../gui/*.cpp ../gui/*.h
./indent ../hkl/*.[ch] ../test/*.[ch]../test/hkl/*.[ch] ../test/hkl3d/*.[ch]
./indent-c++ ../gui/*.cpp ../gui/*.h
