#!/bin/bash
find .. -name "*flymake*" -exec rm -f {} \;
./cleanfile ../hkl.h ../hkl/*.[ch] ../tests/*.[ch] ../tests/tap/*.[ch] ../gui/*.[ch]
./indent ../hkl.h ../hkl/*.[ch] ../tests/*.[ch] ../tests/tap/*.[ch] ../gui/*.[ch]
./indent-c++ ../hkl3d/*.cpp ../hkl3d/*.h
find .. -name "*flymake*" -exec rm -f {} \;
