#!/bin/bash
# PUBLIC DOMAIN
if [ -z "$1" ]; then
    echo  usage: $0 file-to-indent file2 file3 ...
    exit 1
fi

for i in $@; do
    echo Loading $i
    emacs --batch --load ~/.emacs --file $i \
	-f c-mode --eval "(indent-region (point-min) (point-max) nil)" -f save-buffer
done

