# vi:filetype=python:expandtab:tabstop=2:shiftwidth=2
Import('env')
import os

lenv = env.Clone()

sources = Split("""
                hkl-macros.h
                hkl-vector.h
                hkl-matrix.h
                hkl-quaternion.h
                hkl-interval.h
                hkl-source.h
                hkl-axis.h
                hkl-list.h
                hkl-holder.h
                hkl-geometry.h
                hkl-geometry-factory.h
                hkl-detector.h
                hkl-parameter.h
                hkl-lattice.h
                hkl-sample.h
                hkl-pseudoaxis.h
                """)

headers = [ os.path.join('hkl', f) for f in sources ]
lenv.Install(headers)
