Import('env')

myenv = env.Copy()

myenv.Append(CPPPATH = ['#include'])

libhkl_files = Split("""
                        HKLException.cpp
                        svector.cpp
                        smatrix.cpp
                        quaternion.cpp
                        crystal.cpp
                        source.cpp
                        axe.cpp
                        angleconfiguration.cpp
                        angleconfiguration_eulerian4C.cpp
                        angleconfiguration_eulerian6C.cpp
                        angleconfiguration_kappa4C.cpp
                        reflection.cpp
                        diffractometer.cpp
                        diffractometer_eulerian4C.cpp
                        diffractometer_eulerian6C.cpp
                        diffractometer_kappa4C.cpp
                        mode.cpp
                        mode_eulerian4C.cpp
                        mode_eulerian6C.cpp
                        object.cpp
                        value.cpp
                        range.cpp
                        fitparameter.cpp
                        fitparameterlist.cpp
                        affinement.cpp
                        affinement_simplex.cpp       
                        """)

myenv.Library('libhkl', libhkl_files)
