#! /usr/bin/env python
# encoding: utf-8

obj = bld.new_task_gen(
	features = ['cc', 'cshlib'],
	cflags = ['-g', '-Wall', '-Wno-uninitialized', '-Wcast-align', '-Wformat-security'],
	linkflag = ['-g'],
	target = 'hkl',
	uselib = ['GSL'],
	includes = ['../include'],
	vnum = bld.env['HKL_VERSION'])
obj.find_sources_in_dirs('.')
